title: Sam的博客
email: zachaxy@gmail.com
description: 欢迎来到我的博客
baseurl: ""
url: "https://zachaxy.github.io"

github_username: zachaxy

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
